// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdtjsbeoqakmbqsgtenr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkdGpzYmVvcWFrbWJxc2d0ZW5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNjEyODgsImV4cCI6MjA2NzYzNzI4OH0.Fr1cnq5G21joSqggFdXjReIx4QU-pcxAA-uD48pWNSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});